import _ from 'lodash';
import { crearVarianteSinCampo } from '../../common/utils/utils';

const JSON_MINIMO_VALIDO = {
  "entidadDespachadoraCodificadorId": 598,
  "configuracionDestinatarios": {
    "destinatarios": [
      {
        "entidadDestinatariaCodificadorId": 175,
        "isEnCopia": false
      },
      {
        "entidadDestinatariaCodificadorId": 156,
        "isEnCopia": false
      },
      {
        "entidadDestinatariaCodificadorId": 27,
        "isEnCopia": false
      }
    ],
    "destinatariosReferenciados": []
  },
  "materia": "AUT-materia-TEST",
  "idTipoDocumentoOficial": 1,
  "folio": "FOLIO-BASE-2025",
  "usuarioSolicitante": {
    "dv": "1",
    "run": 11111111
  }
};

// --- 2. ESTRUCTURA "HAPPY PATH" COMPLETA ---
const JSON_CON_ARCHIVOS_ANEXOS = {
  ...JSON_MINIMO_VALIDO,
  "archivosAnexosInfo": [
    {
      "fileName": "MINVU.pdf",
      "isReservado": false
    }
  ]
};

const JSON_CON_ARCHIVOS_ANEXOS_VACIOS = {
  ...JSON_MINIMO_VALIDO,
  "archivosAnexosInfo": []
};

// --- VARIACIONES INVÁLIDAS (Campos Eliminados, Sin Datos) ---
// Campo entidadDespachadoraCodificadorId
const SIN_ENTIDAD_DESPACHADORA_CODIFICADOR_ID = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'entidadDespachadoraCodificadorId');
// Campo configuracionDestinatarios y sus subcampos
const SIN_CONFIGURACION_DESTINATARIOS = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'configuracionDestinatarios');
// Campo configuracionDestinatarios.destinatarios y sus subcampos
const SIN_DESTINATARIOS_CONFIGURACION_DESTINATARIOS = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'configuracionDestinatarios.destinatarios');
// Campo configuracionDestinatarios.destinatarios.0.entidadDestinatariaCodificadorId
const SIN_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_CONFIGURACION_DESTINATARIOS = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'configuracionDestinatarios.destinatarios.0.entidadDestinatariaCodificadorId');
// Campo configuracionDestinatarios.destinatarios.0.isEnCopia
const SIN_IS_EN_COPIA_DESTINATARIOS_CONFIGURACION_DESTINATARIOS = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'configuracionDestinatarios.destinatarios.0.isEnCopia');
// Campo configuracionDestinatarios.destinatarios como array vacío
const INFO_VACIO_DESTINATARIOS_CONFIGURACION_DESTINATARIOS = { ...JSON_MINIMO_VALIDO, "configuracionDestinatarios.destinatarios": [] };
// Campo configuracionDestinatarios.destinatariosReferenciados
const SIN_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'configuracionDestinatarios.destinatariosReferenciados');
// Campo configuracionDestinatarios.destinatariosReferenciados como array vacío
const INFO_VACIO_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS = { ...SIN_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS, "configuracionDestinatarios.destinatariosReferenciados": [] };
// Campo configuracionDestinatarios como objeto vacío
const INFO_VACIO_CONFIGURACION_DESTINATARIOS = { ...SIN_CONFIGURACION_DESTINATARIOS, "configuracionDestinatarios": {} };
// Campo folio
const SIN_FOLIO = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'folio');
// Campo idTipoDocumentoOficial
const SIN_ID_TIPO_DOCUMENTO_OFICIAL = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'idTipoDocumentoOficial');
// Campo materia
const SIN_MATERIA = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'materia');

// Campo usuarioSolicitante
const SIN_USUARIO_SOLICITANTE = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'usuarioSolicitante');
// Campo usuarioSolicitante.run
const SIN_RUN_USUARIO_SOLICITANTE = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'usuarioSolicitante.run');
// Campo usuarioSolicitante.dv
const SIN_DV_USUARIO_SOLICITANTE = crearVarianteSinCampo(JSON_MINIMO_VALIDO, 'usuarioSolicitante.dv');
// Campo usuarioSolicitante como objeto vacío
const INFO_VACIO_USUARIO_SOLICITANTE = { ...SIN_USUARIO_SOLICITANTE, "usuarioSolicitante": {} };

const JSON_SWAGGER_MINIMUM = { ...SIN_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS };

// --- 4. VARIACIONES INVÁLIDAS (Tipos de Datos Incorrectos) ---
// Campo entidadDespachadoraCodificadorId
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: "598" };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: "#//´¨" };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: true };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: [] };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: [598] };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_VACIO = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: {} };
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_CON_DATO = { ...JSON_MINIMO_VALIDO, entidadDespachadoraCodificadorId: { entidadDespachadoraCodificadorId: 598 } };
// --- VARIACIONES INVÁLIDAS (Reglas de Dominio) ---
const JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_SIN_DATO = { ...SIN_ENTIDAD_DESPACHADORA_CODIFICADOR_ID, "entidadDespaohadoraCodificadorId": 0 }; // Viola >= 1

// Campo configuracionDestinatarios y sus subcampos
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_INTEGER = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: 12 };
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: "Dato String" };
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: "#//´¨" };
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: false };
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: [] };
const JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, configuracionDestinatarios: [{ destinatarios: [], destinatariosReferenciados: [] }] };
// Campo configuracionDestinatarios.destinatarios y sus subcampos
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_INTEGER = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: 12,
    destinatariosReferenciados: []
  }
};
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: "Dato String",
    destinatariosReferenciados: []
  }
};
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: "#//´¨",
    destinatariosReferenciados: []
  }
};
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_BOOLEAN = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: true,
    destinatariosReferenciados: []
  }
};
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: [],
    destinatariosReferenciados: []
  }
};
const JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: [27],
    destinatariosReferenciados: []
  }
};
// Campo configuracionDestinatarios.destinatarios.0.entidadDestinatariaCodificadorId
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": "27",
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": "#//´¨",
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_BOOLEAN = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": true,
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": [],
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": [27],
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": {},
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
const JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": { entidadDestinatariaCodificadorId: 27 },
      "isEnCopia": false
    },
    destinatariosReferenciados: []
  }
};
// Campo configuracionDestinatarios.destinatarios.0.isEnCopia
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": "false"
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": "#//´¨"
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_INTEGER = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": 1
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": []
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": [false]
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": {}
    },
    destinatariosReferenciados: []
  }
};
const JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatarios: {
      "entidadDestinatariaCodificadorId": 27,
      "isEnCopia": { isEnCopia: false }
    },
    destinatariosReferenciados: []
  }
};

// Campo configuracionDestinatarios.destinatariosReferenciados
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: "String"
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: "#//´¨"
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_INTEGER = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: 2
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_BOOLEAN = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: true
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: [2]
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_VACIO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: {}
  }
};
const JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  configuracionDestinatarios: {
    destinatariosReferenciados: { destinatariosReferenciados: 1 }
  }
};

// Campo folio
const JSON_FOLIO_STRING_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, "folio": "#//´,¨." };
const JSON_FOLIO_STRING_A_INTEGER = { ...JSON_MINIMO_VALIDO, "folio": 12345 };
const JSON_FOLIO_STRING_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, "folio": true };
const JSON_FOLIO_STRING_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, "folio": [] };
const JSON_FOLIO_STRING_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, "folio": [12345] };
const JSON_FOLIO_STRING_A_OBJECT_VACIO = { ...JSON_MINIMO_VALIDO, "folio": {} };
const JSON_FOLIO_STRING_A_OBJECT_CON_DATO = { ...JSON_MINIMO_VALIDO, "folio": { folio: 12345 } };

// Campo idTipoDocumentoOficial
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": "1" };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": "#//´,¨." };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": true };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": [] };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": [12345] };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_VACIO = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": {} };
const JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_CON_DATO = { ...JSON_MINIMO_VALIDO, "idTipoDocumentoOficial": { idTipoDocumentoOficial: 12345 } };

// Campo materia
const JSON_MATERIA_STRING_A_NUMBER = { ...JSON_MINIMO_VALIDO, "materia": 12345 };
const JSON_MATERIA_STRING_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, "materia": "#//´,¨." };
const JSON_MATERIA_STRING_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, "materia": true };
const JSON_MATERIA_STRING_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, "materia": [] };
const JSON_MATERIA_STRING_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, "materia": [12345] };
const JSON_MATERIA_STRING_A_OBJECT_VACIO = { ...JSON_MINIMO_VALIDO, "materia": {} };
const JSON_MATERIA_STRING_A_OBJECT_CON_DATO = { ...JSON_MINIMO_VALIDO, "materia": { idTipoDocumentoOficial: 12345 } };
// --- VARIACIONES INVÁLIDAS (Reglas de Dominio) ---
const JSON_MATERIA_STRING_A_VACIA = { ...JSON_MINIMO_VALIDO, "materia": "" }; // Viola [1, 150]
const JSON_MATERIA_STRING_A_EXCEDE_DATO_LARGO = { ...JSON_MINIMO_VALIDO, "materia": "a".repeat(151) }; // Viola [1, 150]

// Campo usuarioSolicitante
const JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": "String" };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING_CARACTER_ESPECIAL = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": "#//´,¨." };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_NUMBER = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": 12345 };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_BOOLEAN = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": true };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_VACIO = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": [] };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_CON_DATO = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": [12345] };
const JSON_USUARIO_SOLICITENTE_OBJECT_A_OBJECT_CON_DATO = { ...JSON_MINIMO_VALIDO, "usuarioSolicitante": { usuarioSolicitante: 12345 } };

// Campo usuarioSolicitante.dv  
const JSON_DV_SRING_A_NUMBER = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: 1
  }
};
const JSON_DV_SRING_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: "#//´,¨."
  }
};
const JSON_DV_SRING_A_BOOLEAN = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: true
  }
};
const JSON_DV_SRING_A_ARRAY_VACIO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: []
  }
};
const JSON_DV_SRING_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: [1]
  }
};
const JSON_DV_SRING_A_OBJECT = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: {}
  }
};
const JSON_DV_SRING_A_OBJECT_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    dv: { dv: 1 }
  }
};

// Campo usuarioSolicitante.run  
const JSON_DV_INTEGER_A_STRING = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: "11111111"
  }
};
const JSON_DV_INTEGER_A_STRING_CARACTER_ESPECIAL = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: "#//´,¨."
  }
};
const JSON_DV_INTEGER_A_BOOLEAN = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: true
  }
};
const JSON_DV_INTEGER_A_ARRAY_VACIO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: []
  }
};
const JSON_DV_INTEGER_A_ARRAY_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: [11111111]
  }
};
const JSON_DV_INTEGER_A_OBJECT = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: {}
  }
};
const JSON_DV_INTEGER_A_OBJECT_CON_DATO = {
  ...JSON_MINIMO_VALIDO,
  usuarioSolicitante: {
    run: { run: 11111111 }
  }
};

// Body con opcionales para probar reglas anidadas
const JSON_CON_ARCHIVOS_ANEXOS_FILENAME_CORTO = {
  ...JSON_MINIMO_VALIDO,
  "archivosAnexosInfo": [{ "fileName": "ab", "isReservado": false }] // Viola [3, 150]
};
const JSON_CON_ARCHIVOS_ANEXOS_FILENAME_LARGO = {
  ...JSON_MINIMO_VALIDO,
  "archivosAnexosInfo": [{ "fileName": "a".repeat(151) + ".pdf", "isReservado": false }]// Viola [3, 150]
};



export const comunicacionRequest = {
  // Happy Paths
  "JSON_MINIMO_VALIDO": JSON_MINIMO_VALIDO,
  "JSON_CON_ARCHIVOS_ANEXOS": JSON_CON_ARCHIVOS_ANEXOS,
  "JSON_SWAGGER_MINIMUM": JSON_SWAGGER_MINIMUM,
  "JSON_CON_ARCHIVOS_ANEXOS_VACIOS": JSON_CON_ARCHIVOS_ANEXOS_VACIOS,
  "JSON_CON_ARCHIVOS_ANEXOS_FILENAME_CORTO": JSON_CON_ARCHIVOS_ANEXOS_FILENAME_CORTO,
  "JSON_CON_ARCHIVOS_ANEXOS_FILENAME_LARGO": JSON_CON_ARCHIVOS_ANEXOS_FILENAME_LARGO,

  // --- VARIACIONES INVÁLIDAS ---
  "JSON_SIN_CONFIGURACION_DESTINATARIOS": SIN_CONFIGURACION_DESTINATARIOS,
  "JSON_SIN_DESTINATARIOS_CONFIGURACION_DESTINATARIOS": SIN_DESTINATARIOS_CONFIGURACION_DESTINATARIOS,
  "JSON_SIN_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_CONFIGURACION_DESTINATARIOS": SIN_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_CONFIGURACION_DESTINATARIOS,
  "JSON_SIN_IS_EN_COPIA_DESTINATARIOS_CONFIGURACION_DESTINATARIOS": SIN_IS_EN_COPIA_DESTINATARIOS_CONFIGURACION_DESTINATARIOS,
  "JSON_INFO_VACIO_DESTINATARIOS_CONFIGURACION_DESTINATARIOS": INFO_VACIO_DESTINATARIOS_CONFIGURACION_DESTINATARIOS,
  "JSON_SIN_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS": SIN_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS,
  "JSON_INFO_VACIO_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS": INFO_VACIO_DESTINATARIOS_REFERENCIADOS_CONFIGURACION_DESTINATARIOS,
  "JSON_INFO_VACIO_CONFIGURACION_DESTINATARIOS": INFO_VACIO_CONFIGURACION_DESTINATARIOS,
  "JSON_SIN_ENTIDAD_DESPACHADORA_CODIFICADOR_ID": SIN_ENTIDAD_DESPACHADORA_CODIFICADOR_ID,
  "JSON_SIN_FOLIO": SIN_FOLIO,
  "JSON_SIN_ID_TIPO_DOCUMENTO_OFICIAL": SIN_ID_TIPO_DOCUMENTO_OFICIAL,
  "JSON_SIN_MATERIA": SIN_MATERIA,
  "JSON_SIN_USUARIO_SOLICITANTE": SIN_USUARIO_SOLICITANTE,
  "JSON_SIN_RUN_USUARIO_SOLICITANTE": SIN_RUN_USUARIO_SOLICITANTE,
  "JSON_SIN_DV_USUARIO_SOLICITANTE": SIN_DV_USUARIO_SOLICITANTE,
  "JSON_INFO_VACIO_USUARIO_SOLICITANTE": INFO_VACIO_USUARIO_SOLICITANTE,

  // --- Tipos de Dato Incorrectos ---
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING_CARACTER_ESPECIAL": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_STRING_CARACTER_ESPECIAL,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_BOOLEAN": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_BOOLEAN,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_VACIO": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_VACIO,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_CON_DATO": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_ARRAY_CON_DATO,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_VACIO": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_VACIO,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_CON_DATO": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_OBJECT_CON_DATO,
  "JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_SIN_DATO": JSON_ENTIDAD_DESPACHADORA_CODIFICADOR_ID_INTEGER_A_SIN_DATO,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_INTEGER": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_INTEGER,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING_CARACTER_ESPECIAL": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_STRING_CARACTER_ESPECIAL,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_BOOLEAN": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_BOOLEAN,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_VACIO": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_VACIO,
  "JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_CON_DATO": JSON_CONFIGURACION_DESTINATARIOS_OBJECT_A_ARRAY_CON_DATO,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_INTEGER": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_INTEGER,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING_CARACTER_ESPECIAL": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_STRING_CARACTER_ESPECIAL,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_BOOLEAN": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_BOOLEAN,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_VACIO": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_VACIO,
  "JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_CON_DATO": JSON_DESTINATARIOS_CONFIGURACION_DESTINATARIOS_ARRAY_OBJ_A_ARRAY_CON_DATO,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING_CARACTER_ESPECIAL": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_STRING_CARACTER_ESPECIAL,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_BOOLEAN": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_BOOLEAN,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_VACIO": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_VACIO,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_CON_DATO": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_ARRAY_CON_DATO,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_VACIO": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_VACIO,
  "JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_CON_DATO": JSON_ENTIDAD_DESTINATARIA_CODIFICADOR_ID_DESTINATARIOS_INTEGER_A_OBJECT_CON_DATO,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING_CARACTER_ESPECIAL": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_STRING_CARACTER_ESPECIAL,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_INTEGER": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_INTEGER,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_VACIO": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_VACIO,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_CON_DATO": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_ARRAY_CON_DATO,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_VACIO": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_VACIO,
  "JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_CON_DATO": JSON_IS_EN_COPIA_DESTINATARIOS_BOOLEAN_A_OBJECT_CON_DATO,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING_CARACTER_ESPECIAL": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_STRING_CARACTER_ESPECIAL,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_INTEGER": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_INTEGER,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_BOOLEAN": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_BOOLEAN,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_ARRAY_CON_DATO": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_ARRAY_CON_DATO,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_VACIO": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_VACIO,
  "JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_CON_DATO": JSON_DESTINATARIOS_REFERENCIADOS_ARRAY_A_OBJECT_CON_DATO,
  "JSON_FOLIO_STRING_A_STRING_CARACTER_ESPECIAL": JSON_FOLIO_STRING_A_STRING_CARACTER_ESPECIAL,
  "JSON_FOLIO_STRING_A_INTEGER": JSON_FOLIO_STRING_A_INTEGER,
  "JSON_FOLIO_STRING_A_BOOLEAN": JSON_FOLIO_STRING_A_BOOLEAN,
  "JSON_FOLIO_STRING_A_ARRAY_VACIO": JSON_FOLIO_STRING_A_ARRAY_VACIO,
  "JSON_FOLIO_STRING_A_ARRAY_CON_DATO": JSON_FOLIO_STRING_A_ARRAY_CON_DATO,
  "JSON_FOLIO_STRING_A_OBJECT_VACIO": JSON_FOLIO_STRING_A_OBJECT_VACIO,
  "JSON_FOLIO_STRING_A_OBJECT_CON_DATO": JSON_FOLIO_STRING_A_OBJECT_CON_DATO,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING_CARACTER_ESPECIAL": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_STRING_CARACTER_ESPECIAL,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_BOOLEAN": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_BOOLEAN,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_VACIO": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_VACIO,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_CON_DATO": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_ARRAY_CON_DATO,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_VACIO": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_VACIO,
  "JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_CON_DATO": JSON_ID_TIPO_DOCUMENTO_OFICIAL_INTEGER_A_OBJECT_CON_DATO,
  "JSON_MATERIA_STRING_A_NUMBER": JSON_MATERIA_STRING_A_NUMBER,
  "JSON_MATERIA_STRING_A_STRING_CARACTER_ESPECIAL": JSON_MATERIA_STRING_A_STRING_CARACTER_ESPECIAL,
  "JSON_MATERIA_STRING_A_BOOLEAN": JSON_MATERIA_STRING_A_BOOLEAN,
  "JSON_MATERIA_STRING_A_ARRAY_VACIO": JSON_MATERIA_STRING_A_ARRAY_VACIO,
  "JSON_MATERIA_STRING_A_ARRAY_CON_DATO": JSON_MATERIA_STRING_A_ARRAY_CON_DATO,
  "JSON_MATERIA_STRING_A_OBJECT_VACIO": JSON_MATERIA_STRING_A_OBJECT_VACIO,
  "JSON_MATERIA_STRING_A_OBJECT_CON_DATO": JSON_MATERIA_STRING_A_OBJECT_CON_DATO,
  "JSON_MATERIA_STRING_A_VACIA": JSON_MATERIA_STRING_A_VACIA,
  "JSON_MATERIA_STRING_A_EXCEDE_DATO_LARGO": JSON_MATERIA_STRING_A_EXCEDE_DATO_LARGO,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING": JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING_CARACTER_ESPECIAL": JSON_USUARIO_SOLICITENTE_OBJECT_A_STRING_CARACTER_ESPECIAL,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_NUMBER": JSON_USUARIO_SOLICITENTE_OBJECT_A_NUMBER,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_BOOLEAN": JSON_USUARIO_SOLICITENTE_OBJECT_A_BOOLEAN,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_VACIO": JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_VACIO,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_CON_DATO": JSON_USUARIO_SOLICITENTE_OBJECT_A_ARRAY_CON_DATO,
  "JSON_USUARIO_SOLICITENTE_OBJECT_A_OBJECT_CON_DATO": JSON_USUARIO_SOLICITENTE_OBJECT_A_OBJECT_CON_DATO,
  // Campo usuarioSolicitante.dv  
  "JSON_DV_SRING_A_NUMBER": JSON_DV_SRING_A_NUMBER,
  "JSON_DV_SRING_A_STRING_CARACTER_ESPECIAL": JSON_DV_SRING_A_STRING_CARACTER_ESPECIAL,
  "JSON_DV_SRING_A_BOOLEAN": JSON_DV_SRING_A_BOOLEAN,
  "JSON_DV_SRING_A_ARRAY_VACIO": JSON_DV_SRING_A_ARRAY_VACIO,
  "JSON_DV_SRING_A_ARRAY_CON_DATO": JSON_DV_SRING_A_ARRAY_CON_DATO,
  "JSON_DV_SRING_A_OBJECT": JSON_DV_SRING_A_OBJECT,
  "JSON_DV_SRING_A_OBJECT_CON_DATO": JSON_DV_SRING_A_OBJECT_CON_DATO,
  // Campo usuarioSolicitante.run  
  "JSON_DV_INTEGER_A_STRING": JSON_DV_INTEGER_A_STRING,
  "JSON_DV_INTEGER_A_STRING_CARACTER_ESPECIAL": JSON_DV_INTEGER_A_STRING_CARACTER_ESPECIAL,
  "JSON_DV_INTEGER_A_BOOLEAN": JSON_DV_INTEGER_A_BOOLEAN,
  "JSON_DV_INTEGER_A_ARRAY_VACIO": JSON_DV_INTEGER_A_ARRAY_VACIO,
  "JSON_DV_INTEGER_A_ARRAY_CON_DATO": JSON_DV_INTEGER_A_ARRAY_CON_DATO,
  "JSON_DV_INTEGER_A_OBJECT": JSON_DV_INTEGER_A_OBJECT,
  "JSON_DV_INTEGER_A_OBJECT_CON_DATO": JSON_DV_INTEGER_A_OBJECT_CON_DATO,

}